// sandbox/react/Counter.tsx
import { useState } from "react";

type Props = {
  initialCount?: string;
};

export default function Counter({ initialCount = "0" }: Props) {
  const [count, setCount] = useState(Number(initialCount) || 0);

  return (
    <button type="button" onClick={() => setCount(count + 1)}>
      Count: {count}
    </button>
  );
}

// demo/solid/Counter.tsx
import { createSignal } from "solid-js";

type Props = {
  initialCount?: string;
};

export default function Counter(props: Props) {
  const [count, setCount] = createSignal(Number(props.initialCount) || 0);
  return (
    <button type="button" onClick={() => setCount((c) => c + 1)}>
      Count: {count()}
    </button>
  );
}
